// Development-only fixture generated by the real Rust AppService example.
// This adapter has no file access, analysis, or production fallback.
import fixture from "./test-fixtures/session.json";
import { sessionSchema, validateWaveform, type Backend } from "./model";
const session = sessionSchema.parse(fixture.session);
export const previewBackend: Backend = {
  currentSession: async () => session,
  chooseFile: async () => null,
  startImport: async () => {
    throw new Error("开发预览不支持导入");
  },
  jobStatus: async () => {
    throw new Error("开发预览没有后台任务");
  },
  cancelJob: async () => {},
  waveform: async (current, viewport) =>
    validateWaveform(fixture.waveform, current, viewport),
};
